In [8]:
import pandas as pd
import numpy as np
from src.data_prep import load_data, correlation_ratio

df = load_data('data/Exam_Score_Prediction.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        20000 non-null  int64
 1   age               20000 non-null  int64
 2   gender            20000 non-null  object
 3   course            20000 non-null  object
 4   study_hours       20000 non-null  float64
 5   class_attendance  20000 non-null  float64
 6   internet_access   20000 non-null  object
 7   sleep_hours       20000 non-null  float64
 8   sleep_quality     20000 non-null  object
 9   study_method      20000 non-null  object
 10  facility_rating   20000 non-null  object
 11  exam_difficulty   20000 non-null  object
 12  exam_score        20000 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 2.0+ MB

In [9]:
# Разделение колонок по типам данных
col_num = df.select_dtypes(include=['number']).columns.tolist()
col_str = df.select_dtypes(include=['object', 'string']).columns.tolist()

# Проверка результатов
print(f"(col_num), Len { len(col_num)}: {col_num}")
print(f"(col_str), Len {len(col_str)}: {col_str}")

(col_num), Len 6: ['student_id', 'age', 'study_hours', 'class_attendance', 'sleep_hours', 'exam_score']
(col_str), Len 7: ['gender', 'course', 'internet_access', 'sleep_quality', 'study_method', 'facility_rating', 'exam_difficulty']

In [10]:
df[col_num].agg(['min', 'max', 'mean', 'median']).round(2)

,student_id,age,study_hours,class_attendance,sleep_hours,exam_score
min,1.0,17.00,0.08,40.60,4.10,19.60
max,20001.0,24.00,7.91,99.40,9.90,100.00
mean,10000.5,20.47,4.01,70.02,7.01,62.51
median,10000.5,20.00,4.04,69.90,7.00,62.60

In [11]:
pd.DataFrame({col: pd.Series(df[col].nunique()) for col in col_str}).fillna('-')

,gender,course,internet_access,sleep_quality,study_method,facility_rating,exam_difficulty
0,3,7,2,3,5,3,3

In [12]:
pd.DataFrame({col: pd.Series(df[col].unique()) for col in col_str}).fillna('-')

,gender,course,internet_access,sleep_quality,study_method,facility_rating,exam_difficulty
0,male,diploma,yes,poor,coaching,low,hard
1,other,bca,no,average,online videos,medium,moderate
2,female,b.sc,-,good,mixed,high,easy
3,-,b.tech,-,-,self-study,-,-
4,-,bba,-,-,group study,-,-
5,-,ba,-,-,-,-,-
6,-,b.com,-,-,-,-,-

In [13]:
corr_matrix = df[col_num].corr(method='pearson')
corr_matrix['exam_score'].sort_values(ascending=False)

exam_score          1.000000
study_hours         0.717788
class_attendance    0.308850
sleep_hours         0.133222
age                 0.006522
student_id          0.003269
Name: exam_score, dtype: float64

In [14]:
results = {}
for col in col_str:
    eta = correlation_ratio(df[col], df['exam_score'])
    results[col] = eta

for col, eta in sorted(results.items(), key=lambda x: x[1], reverse=True):
    print(f"{col}: {eta:.3f}")

sleep_quality: 0.199
study_method: 0.187
facility_rating: 0.163
course: 0.014
internet_access: 0.008
exam_difficulty: 0.005
gender: 0.004